TASK-4C: Please provide a correlation analysis between two different variables/features and argue for the analysis outputs.

In [9]:
"""
Created on Thursday Nov 06 13:14:25 2022

@author: Ahmet Sina Soykan
"""

import numpy as np                                  #importing libraries
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd         

data=pd.read_excel("Temporary_data3_-_Copy.xlsx")   #read the file

Hippovol= data["HIPPOVOL"]                          #"HIPPOVOL" from data equals to "Hippovol"
df = pd.DataFrame(Hippovol)                         #make "Hippovol" to DataFrame
labels=data["NACCMMSE"]                             #read "NACCMMSE" from data and synchronise it as "labels"
label_df = pd.DataFrame(labels)                     #make labels to DataFrame
label_df ["HIPPOVOL"] = df.iloc[:,0]
label_df.corr()                                     #Correlation

          NACCMMSE  HIPPOVOL
NACCMMSE  1.000000  0.448802
HIPPOVOL  0.448802  1.000000